In [1]:
# Import Dependencies
import pandas as pd
from pathlib import Path

In [2]:
# Make a reference to the comic_books_expanded.csv file path
csv_path = Path("Netflix_data.csv")

# Import the comic_books_expanded.csv file as a DataFrame
Netflix_df = pd.read_csv(csv_path, encoding="utf-8")

In [3]:
Netflix_df.head()

,Title,Available Globally?,Release Date,Hours Viewed,Number of Ratings,Rating,Genre,Key Words,Description
0,The Night Agent: Season 1,Yes,2023-03-23,812100000,7696.0,6.0,"['Biography', 'Drama', 'History']","persian empire,empire,5th century b.c.,achaeme...",NaN
1,Ginny & Georgia: Season 2,Yes,2023-01-05,665100000,5216.0,5.7,"['Comedy', 'Drama', 'Romance']","producer,three word title,headstrong,arranged ...",The film follows headstrong Ginny who meets Su...
2,The Glory: Season 1 // 더 글로리: 시즌 1,Yes,2022-12-30,622800000,11869.0,8.4,['Short'],NaN,NaN
3,Wednesday: Season 1,Yes,2022-11-23,507700000,NaN,NaN,['Talk-Show'],youtube video,MsMojo counts down the top 10 Wednesday (2022)...
4,Queen Charlotte: A Bridgerton Story,Yes,2023-05-04,503000000,50077.0,7.4,"['Drama', 'History', 'Romance']","prequel,queen,historical,england,queen charlot...","Betrothed against her will to King George, you..."

In [9]:
test_df = Netflix_df[Netflix_df["Rating"].isnull()]
test_df.head(100)

,Title,Available Globally?,Release Date,Hours Viewed,Number of Ratings,Rating,Genre,Key Words,Description
3,Wednesday: Season 1,Yes,2022-11-23,507700000,NaN,NaN,['Talk-Show'],youtube video,MsMojo counts down the top 10 Wednesday (2022)...
7,Outer Banks: Season 3,Yes,2023-02-23,402500000,NaN,NaN,NaN,NaN,NaN
10,Manifest: Season 4,Yes,2022-11-04,262600000,NaN,NaN,"['Documentary', 'Short']",NaN,NaN
11,Kaleidoscope: Limited Series,Yes,2023-01-01,252500000,NaN,NaN,NaN,NaN,NaN
12,Firefly Lane: Season 2,Yes,2022-12-02,251500000,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
284,Blood & Gold,Yes,2023-05-26,51600000,NaN,NaN,NaN,NaN,NaN
286,The Blacklist: Season 5,No,NaN,51600000,NaN,NaN,"['Documentary', 'Short']",NaN,NaN
287,Little Women: Limited Series // 작은 아씨들: 리미티드 시리즈,No,2022-09-03,51300000,NaN,NaN,NaN,NaN,NaN
297,2 Hearts,No,NaN,50000000,NaN,NaN,NaN,NaN,NaN
298,Suits (2011): Season 6,Yes,NaN,50000000,NaN,NaN,"['Short', 'Comedy']",NaN,NaN